### PR TITLE
Feature/cpdbds 214 retry on deadlock

### PR DESCRIPTION
**Pull request by hoaphanFox**

### CODE REVIEW

**Comment by sajid-moinuddin** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by sajid-moinuddin** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by sajid-moinuddin** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by sajid-moinuddin** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-13**

**Pull request merged**
