### PR TITLE
Cpdbds 322 locking mechasim

### PR DESCRIPTION
**Pull request by hoaphanFox**
This relates to CPDBDS-90 where workflow don't pass a decision node.

### CODE REVIEW

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by jason-shiao** [comment]
:star: PR built and available in a preview environment **fsa-streamotion-conductor-pr-8**

**Comment by hoaphanFox** [comment]
https://github.com/fsa-streamotion/conductor/pull/50

**Pull request closed without merging**
